In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv')

In [3]:
df.head()

,crim,zn,indus,chas,nox,rm,age,dis,rad,tax,ptratio,b,lstat,medv
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [4]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [5]:
from sklearn.model_selection import cross_val_score,KFold
from sklearn.neighbors import KNeighborsRegressor

In [6]:
knn = KNeighborsRegressor()

In [7]:
kfold = KFold(n_splits=5, shuffle=True, random_state=1)
scores = cross_val_score(knn, X, y, cv=kfold, scoring='r2')

In [8]:
scores.mean()

np.float64(0.4761976351913221)

### GridSearchCV

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
knn = KNeighborsRegressor()

In [11]:
param_grid = {
    'n_neighbors':[1,3,5,7,10,12,15,17,20],
    'weights':['uniform','distance'],
    'algorithm':['ball_tree', 'kd_tree', 'brute'],
    'p':[1,2]
}

In [12]:
gcv = GridSearchCV(knn, param_grid, scoring='r2', refit=True, cv=kfold, verbose=2)

In [13]:
gcv.fit(X,y)

Fitting 5 folds for each of 108 candidates, totalling 540 fits
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=5, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=7, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=15, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=17, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=20, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=3, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=5, p=1, weights=distance; total time=   0.0s

GridSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
             estimator=KNeighborsRegressor(),
             param_grid={'algorithm': ['ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [1, 3, 5, 7, 10, 12, 15, 17, 20],
                         'p': [1, 2], 'weights': ['uniform', 'distance']},
             scoring='r2', verbose=2)

In [14]:
gcv.best_params_

{'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [15]:
gcv.best_score_

np.float64(0.6117139367845081)

In [16]:
gcv.cv_results_

{'mean_fit_time': array([0.00262709, 0.00202522, 0.00250468, 0.00227141, 0.00218139,
        0.00214934, 0.00223575, 0.00254049, 0.00322757, 0.0030818 ,
        0.00256176, 0.00266237, 0.00241709, 0.00282912, 0.00221415,
        0.00207095, 0.00215025, 0.00196919, 0.00235891, 0.00231867,
        0.00230913, 0.00248489, 0.00228801, 0.00203171, 0.00211053,
        0.00219035, 0.0021348 , 0.00222607, 0.00227432, 0.00280347,
        0.00202651, 0.00199604, 0.00257821, 0.00267859, 0.0021874 ,
        0.00199823, 0.00312495, 0.00381441, 0.00325527, 0.00210915,
        0.00219088, 0.00251374, 0.00277486, 0.00262609, 0.00252676,
        0.00256677, 0.00220118, 0.00228543, 0.00228295, 0.00245762,
        0.00277696, 0.00255284, 0.00230293, 0.00262461, 0.00272856,
        0.00273223, 0.00222569, 0.0028161 , 0.00266099, 0.00226898,
        0.00220137, 0.00264716, 0.00236144, 0.00221844, 0.00258474,
        0.00260911, 0.00244403, 0.00217957, 0.00223413, 0.00252552,
        0.00321684, 0.00272212, 0.00186596, 0.00224409, 0.00212426,
        0.00241094, 0.00195508, 0.00208826, 0.00207806, 0.0024714 ,
        0.00216174, 0.00274463, 0.00240097, 0.00230417, 0.00205555,
        0.00248566, 0.00229001, 0.00206456, 0.0018856 , 0.00228381,
        0.00283241, 0.00242958, 0.0019146 , 0.00215964, 0.00212178,
        0.0029376 , 0.00209479, 0.00242996, 0.00245137, 0.00208349,
        0.00208673, 0.00204544, 0.00214033, 0.00284257, 0.00189304,
        0.00210071, 0.00200844, 0.00210257]),
 'std_fit_time': array([7.02789473e-04, 2.10751699e-04, 7.52523407e-04, 5.43612283e-04,
        1.69839168e-04, 1.63091065e-04, 1.76559645e-04, 5.32642166e-04,
        4.38163057e-04, 9.62525870e-04, 4.87686387e-04, 2.08237653e-04,
        4.15691199e-04, 7.10500925e-04, 4.95935893e-04, 1.72228235e-04,
        4.44894982e-04, 8.41579896e-05, 4.64655387e-04, 2.24972934e-04,
        4.34650668e-04, 4.09437319e-04, 5.30155255e-04, 1.75894919e-04,
        1.88898028e-04, 2.05064484e-04, 1.06184687e-04, 3.52086186e-04,
        2.74136141e-04, 6.93927481e-04, 1.91397315e-04, 1.92123543e-04,
        4.25350623e-04, 7.08663032e-04, 1.83748975e-04, 1.42241523e-04,
        6.20600841e-04, 1.86461157e-03, 1.01349064e-03, 1.41816501e-04,
        4.78261095e-04, 4.91497842e-04, 5.86646704e-04, 8.10805140e-04,
        4.66042816e-04, 4.90931850e-04, 1.98684237e-04, 3.67623958e-04,
        1.84290165e-04, 6.11961428e-04, 6.07954186e-04, 5.63780658e-04,
        3.15191396e-04, 4.71343475e-04, 6.88449698e-04, 5.52634403e-04,
        2.36340017e-04, 9.53422950e-04, 4.07503512e-04, 2.79915207e-04,
        2.02378442e-04, 4.34030504e-04, 2.87843516e-04, 6.23577219e-05,
        3.27177930e-04, 4.44292203e-04, 3.32558726e-04, 2.67429196e-04,
        4.10697428e-04, 4.20420495e-04, 9.63371903e-04, 9.31856991e-04,
        4.67898235e-04, 3.21336085e-04, 2.51216415e-04, 6.66474315e-04,
        2.65039433e-04, 1.42487002e-04, 2.21996813e-04, 3.06100837e-04,
        2.74611467e-04, 2.44586712e-04, 3.89846168e-04, 2.68765938e-04,
        2.27589266e-04, 5.22180508e-04, 2.20072360e-04, 2.03204064e-04,
        4.18331861e-04, 6.68704112e-04, 6.07027936e-04, 4.03783318e-04,
        2.24120546e-04, 2.40676554e-04, 4.97838948e-04, 7.98028069e-04,
        1.71403320e-04, 3.93638764e-04, 5.98783302e-04, 1.58211479e-04,
        2.94673543e-04, 1.66029152e-04, 5.98009261e-04, 8.32144093e-04,
        2.32028638e-04, 1.26896662e-04, 3.50727328e-04, 1.66359075e-04]),
 'mean_score_time': array([0.00323176, 0.00254025, 0.00309024, 0.00243363, 0.00257645,
        0.00273895, 0.00417714, 0.00290055, 0.00418992, 0.00392151,
        0.00335865, 0.00420356, 0.0036808 , 0.00339317, 0.00322213,
        0.00284715, 0.00304847, 0.00278711, 0.00279913, 0.00299006,
        0.0028338 , 0.00377479, 0.0028966 , 0.00294995, 0.00302315,
        0.0029408 , 0.00293241, 0.00330353, 0.00312414, 0.00392108,
        0.00283895, 0.00306354, 0.00352159, 0.00352101, 0.00302138,
        0.00327168, 0.00309792, 0.00443039, 0.00363951, 0.00234923,
        0.00245962, 0.00265956, 0.00328689, 0.0029902 , 0.00269618,
        0.00276246, 0.00250211, 0.003124  , 0.00277705, 0.00264635,
        0.00310984, 0.00307841, 0.00285473, 0.00329666, 0.00291295,
        0.00292907, 0.00291157, 0.0033988 , 0.00320067, 0.00325928,
        0.00292811, 0.00311837, 0.00312762, 0.00274806, 0.0034461 ,
        0.00328064, 0.00266795, 0.00275965, 0.01140385, 0.00287604,
        0.00389757, 0.00318179, 0.46369271, 0.00560231, 0.01482048,
        0.01423864, 0.00457826, 0.00607858, 0.00542588, 0.00646977,
        0.01285443, 0.00654507, 0.00611625, 0.00612831, 0.00510325,
        0.00698209, 0.01396828, 0.00634961, 0.00423522, 0.00597501,
        0.00615315, 0.00653419, 0.0046339 , 0.00605745, 0.00621486,
        0.00636859, 0.00492463, 0.01391158, 0.00618291, 0.00606146,
        0.00486526, 0.00571713, 0.00584421, 0.0068862 , 0.0049129 ,
        0.00578213, 0.00574408, 0.0062717 ]),
 'std_score_time': array([9.61741398e-04, 1.03517668e-04, 9.33522904e-04, 1.70839954e-04,
        1.63370882e-04, 2.10951056e-04, 3.20579106e-03, 6.72027221e-04,
        1.06523571e-03, 6.32154281e-04, 6.99443501e-04, 2.26234069e-03,
        6.90110089e-04, 5.36841265e-04, 7.34884136e-04, 7.90700146e-04,
        3.53858487e-04, 9.92856952e-05, 1.15115601e-04, 4.20152512e-04,
        1.11460969e-04, 4.49997004e-04, 1.42426350e-04, 3.49826569e-04,
        2.08190893e-04, 3.56878309e-04, 4.89297281e-04, 5.12298384e-04,
        4.50826160e-04, 9.53704087e-04, 4.00387234e-04, 4.51422536e-04,
        5.85110604e-04, 5.39503039e-04, 2.67712306e-04, 5.50217366e-04,
        7.40699334e-04, 1.47643511e-03, 1.46461023e-03, 1.53898895e-04,
        1.72453325e-04, 1.27969004e-04, 5.85354998e-04, 7.80741839e-04,
        5.59999609e-04, 1.31452477e-04, 6.92305690e-04, 6.07390167e-04,
        4.17932452e-04, 1.53676457e-04, 6.34439439e-04, 9.29991995e-04,
        2.25168272e-04, 7.48900885e-04, 4.82885233e-04, 4.66534283e-04,
        3.03709449e-04, 4.00218082e-04, 8.01335798e-04, 7.44678082e-04,
        2.74484906e-04, 3.64127341e-04, 4.42203093e-04, 3.98325183e-04,
        6.75811953e-04, 7.73360135e-04, 1.01657321e-04, 7.04143996e-05,
        1.64196621e-02, 1.77320154e-04, 5.19540805e-04, 2.19252639e-04,
        9.19189878e-01, 5.26837034e-04, 1.77617961e-02, 1.61345489e-02,
        4.38378877e-04, 4.71975760e-04, 5.86405981e-04, 4.47157472e-04,
        1.61213737e-02, 4.02476126e-04, 3.67543242e-04, 5.92607553e-04,
        3.78603497e-04, 1.42751648e-03, 1.66718096e-02, 7.54543771e-04,
        5.80702746e-04, 8.93567847e-04, 4.91785383e-04, 4.34705885e-04,
        5.54814757e-04, 3.03159153e-04, 1.25790077e-03, 9.96432833e-04,
        4.82195681e-04, 1.65584450e-02, 1.00607014e-03, 1.94226469e-04,
        6.51827197e-04, 2.31572057e-04, 8.77389527e-04, 6.78866204e-04,
        4.10447688e-04, 4.77178904e-04, 4.03525924e-04, 2.98385880e-04]),
 'param_algorithm': masked_array(data=['ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'ball_tree', 'ball_tree', 'ball_tree', 'ball_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree', 'kd_tree',
                    'kd_tree', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute', 'brute', 'brute', 'brute', 'brute', 'brute',
                    'brute'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_n_neighbors': masked_array(data=[1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 10, 10,
                    10, 10, 12, 12, 12, 12, 15, 15, 15, 15, 17, 17, 17, 17,
                    20, 20, 20, 20, 1, 1, 1, 1, 3, 3, 3, 3, 5, 5, 5, 5, 7,
                    7, 7, 7, 10, 10, 10, 10, 12, 12, 12, 12, 15, 15, 15,
                    15, 17, 17, 17, 17, 20, 20, 20, 20, 1, 1, 1, 1, 3, 3,
                    3, 3, 5, 5, 5, 5, 7, 7, 7, 7, 10, 10, 10, 10, 12, 12,
                    12, 12, 15, 15, 15, 15, 17, 17, 17, 17, 20, 20, 20, 20],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_p': masked_array(data=[1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
                    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2,
                    1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1,
                    2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2, 1, 1, 2, 2],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=999999),
 'param_weights': masked_array(data=['uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance',
                    'uniform', 'distance', 'uniform', 'distance'],
              mask=[False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False, False, False, False, False,
                    False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'algorithm': 'ball_tree',
   'n_neighbors': 1,
   'p': 1,
   'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 10, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 12, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 15, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 17, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'ball_tree', 'n_neighbors': 20, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 1, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 3, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 5, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 1, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 7, 'p': 2, 'weights': 'distance'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'uniform'},
  {'algorithm': 'kd_tree', 'n_neighbors': 10, 'p': 1, 'weights': 'distance'},

In [17]:
pd.DataFrame(gcv.cv_results_)[['param_algorithm',	'param_n_neighbors',	'param_p', 'param_weights', 'mean_test_score']].sort_values('mean_test_score',ascending=False)

   param_algorithm  param_n_neighbors  param_p param_weights  mean_test_score
81           brute                  5        1      distance         0.611714
45         kd_tree                  5        1      distance         0.611714
9        ball_tree                  5        1      distance         0.611714
49         kd_tree                  7        1      distance         0.605716
85           brute                  7        1      distance         0.605716
..             ...                ...      ...           ...              ...
38         kd_tree                  1        2       uniform         0.331522
2        ball_tree                  1        2       uniform         0.331522
75           brute                  1        2      distance         0.331522
39         kd_tree                  1        2      distance         0.331522
3        ball_tree                  1        2      distance         0.331522

[108 rows x 5 columns]

In [19]:
new_data = pd.DataFrame([
    [0.1, 18.0, 2.31, 0, 0.538, 6.575, 65.2, 4.09, 1, 296, 15.3, 396.9, 4.98]
], columns=X.columns)

gcv.predict(new_data)

array([23.98446316])

In [20]:
gcv.predict(new_data)

array([23.98446316])

### RandomizedSearchCV

In [21]:
from sklearn.model_selection import RandomizedSearchCV

In [22]:
rcv = RandomizedSearchCV(knn, param_grid, scoring='r2', refit=True, cv=kfold, verbose=2)

In [23]:
rcv.fit(X,y)

Fitting 5 folds for each of 10 candidates, totalling 50 fits
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=20, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=17, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=1, p=1, weights=uniform; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=3, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=5, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=ball_tree, n_neighbors=10, p=1, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=brute, n_neighbors=12, p=2, weights=distance; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s
[CV] END algorithm=kd_tree, n_neighbors=1, p=2, weights=uniform; total time=   0.0s

RandomizedSearchCV(cv=KFold(n_splits=5, random_state=1, shuffle=True),
                   estimator=KNeighborsRegressor(),
                   param_distributions={'algorithm': ['ball_tree', 'kd_tree',
                                                      'brute'],
                                        'n_neighbors': [1, 3, 5, 7, 10, 12, 15,
                                                        17, 20],
                                        'p': [1, 2],
                                        'weights': ['uniform', 'distance']},
                   scoring='r2', verbose=2)

In [24]:
rcv.best_score_

np.float64(0.6117139367845081)

In [25]:
rcv.best_params_

{'weights': 'distance', 'p': 1, 'n_neighbors': 5, 'algorithm': 'brute'}